### ISSUE TITLE
On ERR_NETWORK_CHANGED Reload

### ISSUE THREAD

**Issue by alexandre433** [RaiderIO/raiderio-client-builds#1]
Hello,

I've been having this, let's call it "issue", and it happens every time I "unsleep" my computer.
I'd recommend reloading after it gains access to the internet again. This happens due to the computer going to sleep and not having internet connection what so ever.

Thank You In Advance For Reading !

**Comment by jahraphael** [comment]
We have a new release coming out "soon" (really) that will address this issue.  What we are doing in the new build is just ensuring that the periodic refresh doesn't get canceled if a network error occurs.  So after you unsleep your computer then it should take a couple of minutes then the next auto refresh will kick in and it will get the latest data.
