### ISSUE TITLE
Linux appimage 1.6.0

### ISSUE THREAD

**Issue by ubkma** [RaiderIO/raiderio-client-builds#2]
Initially can't find WTF folder.  Manually updated config.json to include that.
Hangs with message in terminal:
Initializing error tracker...
23:09:02.219 › [Main]: RaiderIO Client starting up...
23:09:02.347 › [ConfigService]: Loading from /home/kevin/.config/RaiderIO/config.json
-config.json:
{
  "configFormat": "2018-06-17",
  "appVersion": "1.6.0",
  "wowFolder": "/home/kevin/Games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_retail_",
  "channel": "release",
  "installedManifest": {},
  "updateTimerMinutes": 10,
  "hostURL": "https://cdnassets.raider.io",
  "launchAtStartup": false,
  "startMinimized": false,
  "minimizeToTray": true,
  "syncMode": "all",
  "syncAmericasHorde": true,
  "syncAmericasAlliance": true,
  "syncEuropeHorde": true,
  "syncEuropeAlliance": true,
  "syncKoreaHorde": true,
  "syncKoreaAlliance": true,
  "syncTaiwanHorde": true,
  "syncTaiwanAlliance": true,
  "syncCharacterData": true,
  "showScoreColors": true,
  "autoUpdateOnLogout": true,
  "adjustedForPatch81Folder": true,
  "authToken": "",
  "shareUsageAnalytics": false,
  "askedAboutSharingUsageAnalytics": false,
  "sortColumn": "score",
  "sortDirection": "descending"
}

**Comment by jahraphael** [comment]
Thanks for the report. Can you try the build we just uploaded here? https://github.com/RaiderIO/raiderio-client-builds/releases/tag/v1.6.1

**Comment by ubkma** [comment]
New build works great. Getting a warning about using the curseforge updater, which I don't (always update addons manually since such updaters seldom work on Linux), but it doesn't care in the end. Thanks!

**Comment by jahraphael** [comment]
Great! So that warning really just means that it found a version of the addon that didn't come from the client. If you manually installed from a downloaded zip then it would trigger this.

That said, the warning should only happen once when it overwrites the data with the client data.

Are you getting the curseforge updater warning each time you refresh?

**Comment by ubkma** [comment]
No, just got the Curse warning the first time starting.

Also, and not too important once I realized how to prevent it, if the gui is set to minimize to the system tray instead of close on "x", it can't be properly brought back from the system tray.  You just get a black box and have to kill the process to restart the app.  This could be due to Budgie (the WM).  It may be trying to open an additional instance.  I am simply minimizing it to Plank to get it out of the way for now.

**Comment by jahraphael** [comment]
@ubkma - can you try out this new build to see if the tray works properly now? https://github.com/RaiderIO/raiderio-client-builds/releases/tag/v1.6.2

**Comment by ubkma** [comment]
Yes, the system tray functions work now.  Very nice!  It also has the options menu when clicked in the system tray that it lacked before - Open, Refresh, Time last updated, Check for updates, and Quit.

That would seem to have fixed everything I have noted so far.  I will update you if anything else presents itself after further use.

Edit: There may be an issue regarding "Checking for client updates".  It seems to try this automatically and never obtains any info (spinner never stops).
