### ISSUE TITLE
Code signature changed?

### ISSUE THREAD

**Issue by AmnaSN** [RaiderIO/raiderio-client-builds#3]
Just wanted to confirm whether the code signature has chnaged from 'Jah Raphael (L4QNGRZDQ5)' to 'Ludicrous Speed, LLC (LPUJ4TM3WQ)'?

**Comment by jahraphael** [comment]
> Just wanted to confirm whether the code signature has chnaged from 'Jah Raphael (L4QNGRZDQ5)' to 'Ludicrous Speed, LLC (LPUJ4TM3WQ)'?

That's correct. Ludicrous Speed, LLC is just my LLC that owns Raider.IO.

Had it given some kind of notice of the change? Or is it just something you spotted?

**Comment by AmnaSN** [comment]
It is something that I just spotted. Thanks for letting me know.
